# SPDX-License-Identifier: GPL-3.0-or-later
"""Reproduce the shipped Blender browser adapter without the host application.

Blender-only extraction dated 2026-09-21. Rendering functions preserve the
original release generator behavior; unrelated engine/application packaging is
excluded. The historical generated comment is retained for byte correspondence.
"""
from pathlib import Path
import argparse
import json
import re

class BuildError(ValueError):
    pass

class ShellPatchError(BuildError):
    pass

BLENDER_ENTRY_TAG = re.compile(r'<script type="module" src="assets/index-[A-Za-z0-9_-]+\.js"></script>')
_GET_BY_ID = re.compile(r'getElementById\("([A-Za-z0-9_-]+)"\)')
_QUERY_CLASS = re.compile(r'querySelector\("\.([A-Za-z0-9_-]+)"\)')

def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))

def _one(directory: Path, pattern: str) -> Path:
    found = sorted(directory.glob(pattern)) if directory.is_dir() else []
    if len(found) != 1:
        raise BuildError(f"Blender dist must hold exactly one assets/{pattern}; found {len(found)}")
    return found[0]

def blender_dom_contract(entry_module: str) -> tuple[list[str], list[str]]:
    """Element ids and class selectors the vendor entry module looks up at load."""
    return sorted(set(_GET_BY_ID.findall(entry_module))), sorted(set(_QUERY_CLASS.findall(entry_module)))

def render_blender_shell(template: str, entry_name: str, entry_module: str) -> str:
    """Point the template at the build's entry module and check the DOM contract.

    The template carries exactly one module tag for ``assets/index-*.js``; its name
    is replaced with the entry the dist actually holds. Every id and class the vendor
    module looks up must exist in the page, or the bundle throws before it downloads
    anything. No inline script may appear: the Blender CSP carries no hashes.
    """
    out = template.replace("\r\n", "\n")
    hits = len(BLENDER_ENTRY_TAG.findall(out))
    if hits != 1:
        raise ShellPatchError(f"blender shell: {hits} entry module tag(s), expected exactly 1")
    entry_tag = f'<script type="module" src="assets/{entry_name}"></script>'
    out = BLENDER_ENTRY_TAG.sub(lambda _match: entry_tag, out)
    ids, classes = blender_dom_contract(entry_module)
    missing = [f"#{name}" for name in ids if out.count(f'id="{name}"') != 1]
    missing += [f".{name}" for name in classes
                if not re.search(r'class="(?:[^"]*\s)?' + re.escape(name) + r'(?:\s[^"]*)?"', out)]
    if missing:
        raise ShellPatchError("blender shell lacks vendor DOM contract elements: " + ", ".join(missing))
    if re.search(r"<script(?![^>]*\ssrc=)[^>]*>", out, re.IGNORECASE):
        raise ShellPatchError("blender shell carries an inline script; the Blender CSP admits none")
    order = [out.find('<script src="bosonoo/config.js"></script>'), out.find('<script src="bosonoo/storage.js"></script>'),
             out.find('<script src="bosonoo/bridge.js"></script>'),
             out.find(entry_tag)]
    if -1 in order or order != sorted(order) or out.count("<script") != 4:
        raise ShellPatchError("blender shell must load bosonoo/config.js, then bosonoo/storage.js, then bosonoo/bridge.js, then the vendor entry")
    if "http://" in out or "https://" in out:
        raise ShellPatchError("blender shell must not reference any absolute URL")
    return out

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--blender-dist', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    parser.add_argument('--broker-ws', required=True,
                        help='Explicit WebSocket endpoint for your separately implemented host')
    args = parser.parse_args()
    if not args.broker_ws.startswith(('ws://', 'wss://')):
        parser.error('--broker-ws must use ws:// or wss://')
    root = Path(__file__).resolve().parent
    entry = _one(args.blender_dist/'assets', 'index-*.js')
    shell = render_blender_shell(
        (root/'engine-runtime/pack/blender/bosonoo.html').read_text(encoding='utf-8'),
        entry.name, entry.read_text(encoding='utf-8'))
    shell = shell.replace('Bosonoo page for the development Blender pack', 'Bosonoo page for the Blender pack')
    shell = shell.replace('engine-runtime/build_dev_pack.py', 'engine-runtime/build_release_candidate.py')
    label = 'GPL (see NOTICE.txt); development pack, not reviewed'
    if shell.count(label) != 1:
        raise BuildError('Expected exactly one license placeholder')
    shell = shell.replace(label, 'GPL (see NOTICE.txt and COPYING)')
    config = (
        '/* Generated by engine-runtime/build_release_candidate.py; the broker address is baked into\n'
        ' * the pack so the page never takes it from a URL, a cookie or a query string. */\n'
        f'window.BOSONOO_BROKER_WS = {json.dumps(args.broker_ws)};\n')
    args.out.mkdir(parents=True, exist_ok=False)
    _write_text(args.out/'bosonoo.html', shell)
    _write_text(args.out/'bosonoo/config.js', config)
    for source, name in [('engine-runtime/pack/storage.js', 'storage.js'),
                         ('engine-runtime/pack/blender/bridge.js', 'bridge.js'),
                         ('engine-runtime/pack/blender/automation.py', 'automation.py'),
                         ('engine-runtime/pack/blender/session.py', 'session.py')]:
        (args.out/'bosonoo'/name).write_bytes((root/source).read_bytes().replace(b'\r\n', b'\n'))
    print('Reproduced bosonoo.html, bosonoo/{config,storage,bridge}.js and bosonoo/{automation,session}.py')

if __name__ == '__main__':
    main()
